// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/adminInfo": {
            "get": {
                "description": "获取管理员信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "获取管理员信息",
                "operationId": "/admin/adminInfo",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminInfoOut"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/changePwd": {
            "post": {
                "description": "更改密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "更改密码",
                "operationId": "/admin/changePwd",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ChangePwdInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin_login/login": {
            "post": {
                "description": "管理员登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "管理员登录",
                "operationId": "/admin_login/login",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AdminLoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AdminLoginOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin_login/logout": {
            "get": {
                "description": "管理员退出登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员接口"
                ],
                "summary": "管理员退出登录",
                "operationId": "/admin_login/logout",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/appAdd": {
            "post": {
                "description": "租户添加",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户添加",
                "operationId": "/app/appAdd",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.APPAddHttpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/appDelete": {
            "get": {
                "description": "租户删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户删除",
                "operationId": "/app/appDelete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/appDetail": {
            "get": {
                "description": "租户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户详情",
                "operationId": "/app/appDetail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.App"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/appList": {
            "get": {
                "description": "租户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户列表",
                "operationId": "/app/appList",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "info",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页多少条",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "pageNo",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.APPListOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/appStat": {
            "get": {
                "description": "租户统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户统计",
                "operationId": "/app/appStat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "租户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.StatisticsOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/app/appUpdate": {
            "post": {
                "description": "租户更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "租户管理"
                ],
                "summary": "租户更新",
                "operationId": "/app/appUpdate",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.APPUpdateHttpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/main/flowStat": {
            "get": {
                "description": "访问统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "首页大盘"
                ],
                "summary": "访问统计",
                "operationId": "/main/flowStat",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceStatOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/main/panelGroupData": {
            "get": {
                "description": "指标统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "首页大盘"
                ],
                "summary": "指标统计",
                "operationId": "/main/panelGroupData",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PanelGroupOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/main/serviceStat": {
            "get": {
                "description": "服务统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "首页大盘"
                ],
                "summary": "服务统计",
                "operationId": "/main/serviceStat",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceMainStatOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/oauth/tokens": {
            "post": {
                "description": "获取Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OAuth"
                ],
                "summary": "获取Token",
                "operationId": "/oauth/tokens",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.TokensInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.TokensOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceAddGrpc": {
            "post": {
                "description": "添加GRPC服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "添加GRPC服务",
                "operationId": "/service/serviceAddGrpc",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceAddGrpcInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceAddHttp": {
            "post": {
                "description": "添加HTTP服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "添加HTTP服务",
                "operationId": "/service/serviceAddHttp",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceAddHttpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceAddTcp": {
            "post": {
                "description": "添加Tcp服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "添加Tcp服务",
                "operationId": "/service/serviceAddTcp",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceAddTcpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceDelete": {
            "get": {
                "description": "服务删除",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务删除",
                "operationId": "/service/serviceDelete",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceDetail": {
            "get": {
                "description": "服务详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务详情",
                "operationId": "/service/serviceDetail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dao.ServiceDetail"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceList": {
            "get": {
                "description": "服务列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务列表",
                "operationId": "/service/serviceList",
                "parameters": [
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "info",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceStat": {
            "get": {
                "description": "服务统计",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "服务统计",
                "operationId": "/service/serviceStat",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ServiceStatOutput"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceUpdateGrpc": {
            "post": {
                "description": "grpc服务更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "grpc服务更新",
                "operationId": "/service/serviceUpdateGrpc",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceUpdateGrpcInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceUpdateHttp": {
            "post": {
                "description": "更新HTTP服务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "更新HTTP服务",
                "operationId": "/service/serviceUpdateHttp",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceUpdateHttpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/service/serviceUpdateTcp": {
            "post": {
                "description": "tcp服务更新",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "服务管理"
                ],
                "summary": "tcp服务更新",
                "operationId": "/service/serviceUpdateTcp",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ServiceUpdateTcpInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/middleware.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dao.AccessControl": {
            "type": "object",
            "properties": {
                "black_list": {
                    "type": "string"
                },
                "clientip_flow_limit": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "open_auth": {
                    "type": "integer"
                },
                "service_flow_limit": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                },
                "white_host_name": {
                    "type": "string"
                },
                "white_list": {
                    "type": "string"
                }
            }
        },
        "dao.App": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "string"
                },
                "create_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_delete": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "update_at": {
                    "type": "string"
                },
                "white_ips": {
                    "type": "string"
                }
            }
        },
        "dao.GrpcRule": {
            "type": "object",
            "properties": {
                "header_transfor": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                }
            }
        },
        "dao.HttpRule": {
            "type": "object",
            "properties": {
                "header_transfor": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "need_https": {
                    "type": "integer"
                },
                "need_strip_uri": {
                    "type": "integer"
                },
                "need_websocket": {
                    "type": "integer"
                },
                "rule": {
                    "type": "string"
                },
                "rule_type": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                },
                "url_rewrite": {
                    "type": "string"
                }
            }
        },
        "dao.LoadBalance": {
            "type": "object",
            "properties": {
                "check_interval": {
                    "type": "integer"
                },
                "check_method": {
                    "type": "integer"
                },
                "check_timeout": {
                    "type": "integer"
                },
                "forbid_list": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ip_list": {
                    "type": "string"
                },
                "round_type": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                },
                "upstream_connect_timeout": {
                    "type": "integer"
                },
                "upstream_header_timeout": {
                    "type": "integer"
                },
                "upstream_idle_timeout": {
                    "type": "integer"
                },
                "upstream_max_idle": {
                    "type": "integer"
                },
                "weight_list": {
                    "type": "string"
                }
            }
        },
        "dao.ServiceDetail": {
            "type": "object",
            "properties": {
                "accessControl": {
                    "$ref": "#/definitions/dao.AccessControl"
                },
                "grpc": {
                    "$ref": "#/definitions/dao.GrpcRule"
                },
                "http": {
                    "$ref": "#/definitions/dao.HttpRule"
                },
                "info": {
                    "$ref": "#/definitions/dao.ServiceInfo"
                },
                "loadBalance": {
                    "$ref": "#/definitions/dao.LoadBalance"
                },
                "tcp": {
                    "$ref": "#/definitions/dao.TcpRule"
                }
            }
        },
        "dao.ServiceInfo": {
            "type": "object",
            "properties": {
                "create_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_delete": {
                    "type": "integer"
                },
                "load_type": {
                    "type": "integer"
                },
                "service_desc": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                },
                "update_at": {
                    "type": "string"
                }
            }
        },
        "dao.TcpRule": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                }
            }
        },
        "dto.APPAddHttpInput": {
            "type": "object",
            "required": [
                "appId",
                "name"
            ],
            "properties": {
                "appId": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "whiteIps": {
                    "type": "string"
                }
            }
        },
        "dto.APPListItemOutput": {
            "type": "object",
            "properties": {
                "appId": {
                    "type": "string"
                },
                "createAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isDelete": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "realQpd": {
                    "type": "integer"
                },
                "realQps": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "updateAt": {
                    "type": "string"
                },
                "whiteIps": {
                    "type": "string"
                }
            }
        },
        "dto.APPListOutput": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.APPListItemOutput"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.APPUpdateHttpInput": {
            "type": "object",
            "required": [
                "id",
                "name",
                "secret"
            ],
            "properties": {
                "appId": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "qpd": {
                    "type": "integer"
                },
                "qps": {
                    "type": "integer"
                },
                "secret": {
                    "type": "string"
                },
                "whiteIps": {
                    "type": "string"
                }
            }
        },
        "dto.AdminInfoOut": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "introduction": {
                    "type": "string"
                },
                "loginTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.AdminLoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "description": "这里是文档里面的描述",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "dto.AdminLoginOutput": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "token",
                    "type": "string",
                    "example": "token"
                }
            }
        },
        "dto.ChangePwdInput": {
            "type": "object",
            "required": [
                "oldPassWord",
                "password"
            ],
            "properties": {
                "oldPassWord": {
                    "description": "旧密码",
                    "type": "string",
                    "example": "123456"
                },
                "password": {
                    "description": "新密码",
                    "type": "string",
                    "example": "Nbxx12345678"
                }
            }
        },
        "dto.PanelGroupOutput": {
            "type": "object",
            "properties": {
                "appNum": {
                    "description": "租户总数",
                    "type": "integer"
                },
                "currentNum": {
                    "description": "实时请求总数",
                    "type": "integer"
                },
                "serviceNum": {
                    "description": "服务总数",
                    "type": "integer"
                },
                "todayRequestNum": {
                    "description": "今日请求",
                    "type": "integer"
                }
            }
        },
        "dto.ServiceAddGrpcInput": {
            "type": "object",
            "required": [
                "ipList",
                "port",
                "serviceDesc",
                "serviceName",
                "weightList"
            ],
            "properties": {
                "blackList": {
                    "description": "黑名单",
                    "type": "string"
                },
                "clientIpFlowLimit": {
                    "description": "客户端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "forbidList": {
                    "description": "禁用IP列表",
                    "type": "string"
                },
                "headerTransfor": {
                    "description": "header转换",
                    "type": "string"
                },
                "ipList": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "127.0.0.1:80"
                },
                "openAuth": {
                    "description": "是否开启权限",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "port": {
                    "description": "服务描述",
                    "type": "integer",
                    "maximum": 8999,
                    "minimum": 8001,
                    "example": 8888
                },
                "roundType": {
                    "description": "轮询方式",
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 0
                },
                "serviceDesc": {
                    "description": "服务描述",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "我是grpc测试"
                },
                "serviceIpFlowLimit": {
                    "description": "服务端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "serviceName": {
                    "description": "服务名称",
                    "type": "string",
                    "example": "test_grpc01"
                },
                "weightList": {
                    "description": "权重列",
                    "type": "string",
                    "example": "50"
                },
                "whiteHostName": {
                    "description": "白名单主机",
                    "type": "string"
                },
                "whiteList": {
                    "description": "白名单",
                    "type": "string"
                }
            }
        },
        "dto.ServiceAddHttpInput": {
            "type": "object",
            "required": [
                "ipList",
                "rule",
                "serviceDesc",
                "serviceName",
                "weightList"
            ],
            "properties": {
                "blackList": {
                    "description": "黑名单",
                    "type": "string"
                },
                "clientIpFlowLimit": {
                    "description": "客户端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "headerTransfor": {
                    "description": "header转换",
                    "type": "string"
                },
                "ipList": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "127.0.0.1:80"
                },
                "needHttps": {
                    "description": "支持Https",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "needStripUrl": {
                    "description": "启用StripUrl",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "needWebsocket": {
                    "description": "支持Websocket",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "openAuth": {
                    "description": "是否开启权限",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "roundType": {
                    "description": "轮询方式",
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 0
                },
                "rule": {
                    "description": "接入路径",
                    "type": "string",
                    "example": "/testHttpService"
                },
                "ruleType": {
                    "description": "接入类型",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "serviceDesc": {
                    "description": "服务描述",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "test_http_service"
                },
                "serviceIpFlowLimit": {
                    "description": "服务端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "serviceName": {
                    "description": "服务名称",
                    "type": "string",
                    "example": "test_http_service"
                },
                "upstreamConnectTimeout": {
                    "description": "连接超时",
                    "type": "integer",
                    "minimum": 0
                },
                "upstreamHeaderTimeout": {
                    "description": "获取Header超时",
                    "type": "integer",
                    "minimum": 0
                },
                "upstreamIdleTimeout": {
                    "description": "连接最大空闲时间",
                    "type": "integer",
                    "minimum": 0
                },
                "upstreamMaxIdle": {
                    "description": "最大空闲连接数",
                    "type": "integer",
                    "minimum": 0
                },
                "urlRewrite": {
                    "description": "url重写功能",
                    "type": "string"
                },
                "weightList": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "50"
                },
                "whiteList": {
                    "description": "白名单",
                    "type": "string"
                }
            }
        },
        "dto.ServiceAddTcpInput": {
            "type": "object",
            "required": [
                "ipList",
                "port",
                "serviceDesc",
                "serviceName",
                "weightList"
            ],
            "properties": {
                "blackList": {
                    "description": "黑名单",
                    "type": "string"
                },
                "clientIpFlowLimit": {
                    "description": "客户端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "forbidList": {
                    "description": "禁用IP列表",
                    "type": "string"
                },
                "headerTransfor": {
                    "description": "header转换",
                    "type": "string"
                },
                "ipList": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "127.0.0.1:80"
                },
                "openAuth": {
                    "description": "是否开启权限",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "port": {
                    "description": "端口",
                    "type": "integer",
                    "maximum": 8999,
                    "minimum": 8001,
                    "example": 8777
                },
                "roundType": {
                    "description": "轮询方式",
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 0
                },
                "serviceDesc": {
                    "description": "服务描述",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "我是一条测试"
                },
                "serviceIpFlowLimit": {
                    "description": "服务端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "serviceName": {
                    "description": "服务名称",
                    "type": "string",
                    "example": "test_tcp01"
                },
                "weightList": {
                    "description": "权重列",
                    "type": "string",
                    "example": "50"
                },
                "whiteHostName": {
                    "description": "白名单主机",
                    "type": "string"
                },
                "whiteList": {
                    "description": "白名单",
                    "type": "string"
                }
            }
        },
        "dto.ServiceItemOutput": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "load_type": {
                    "description": "类型",
                    "type": "integer"
                },
                "qpd": {
                    "description": "qpd",
                    "type": "integer"
                },
                "qps": {
                    "description": "qps",
                    "type": "integer"
                },
                "service_addr": {
                    "description": "服务地址",
                    "type": "string"
                },
                "service_desc": {
                    "description": "服务描述",
                    "type": "string"
                },
                "service_name": {
                    "description": "服务名称",
                    "type": "string"
                },
                "totalNode": {
                    "description": "节点数",
                    "type": "integer"
                }
            }
        },
        "dto.ServiceMainStatOutput": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "每份数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StatItem"
                    }
                },
                "legend": {
                    "description": "总的数据",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.ServiceOutput": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ServiceItemOutput"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "dto.ServiceStatOutput": {
            "type": "object",
            "properties": {
                "today": {
                    "description": "今日数据统计",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "yesterday": {
                    "description": "昨日数据统计",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.ServiceUpdateGrpcInput": {
            "type": "object",
            "required": [
                "id",
                "ipList",
                "port",
                "serviceDesc",
                "serviceName",
                "weightList"
            ],
            "properties": {
                "blackList": {
                    "description": "黑名单",
                    "type": "string"
                },
                "clientIpFlowLimit": {
                    "description": "客户端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "forbidList": {
                    "description": "禁用IP列表",
                    "type": "string"
                },
                "headerTransfor": {
                    "description": "header转换",
                    "type": "string"
                },
                "id": {
                    "description": "服务编号",
                    "type": "integer",
                    "minimum": 1,
                    "example": 62
                },
                "ipList": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "127.0.0.1:80"
                },
                "openAuth": {
                    "description": "是否开启权限",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "port": {
                    "description": "端口",
                    "type": "integer",
                    "maximum": 8999,
                    "minimum": 8001,
                    "example": 8889
                },
                "roundType": {
                    "description": "轮询方式",
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 0
                },
                "serviceDesc": {
                    "description": "服务描述",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "我是更新测试"
                },
                "serviceIpFlowLimit": {
                    "description": "服务端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "serviceName": {
                    "description": "服务名称",
                    "type": "string",
                    "example": "test_grpc_update01"
                },
                "weightList": {
                    "description": "权重列",
                    "type": "string",
                    "example": "50"
                },
                "whiteHostName": {
                    "description": "白名单主机",
                    "type": "string"
                },
                "whiteList": {
                    "description": "白名单",
                    "type": "string"
                }
            }
        },
        "dto.ServiceUpdateHttpInput": {
            "type": "object",
            "required": [
                "id",
                "ipList",
                "rule",
                "serviceDesc",
                "serviceName",
                "weightList"
            ],
            "properties": {
                "blackList": {
                    "description": "黑名单",
                    "type": "string"
                },
                "clientIpFlowLimit": {
                    "description": "客户端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "headerTransfor": {
                    "description": "header转换",
                    "type": "string"
                },
                "id": {
                    "description": "服务编号",
                    "type": "integer",
                    "minimum": 1,
                    "example": 62
                },
                "ipList": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "127.0.0.1:80"
                },
                "needHttps": {
                    "description": "支持Https",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "needStripUrl": {
                    "description": "启用StripUrl",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "needWebsocket": {
                    "description": "支持Websocket",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "openAuth": {
                    "description": "是否开启权限",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "roundType": {
                    "description": "轮询方式",
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 0
                },
                "rule": {
                    "description": "接入路径",
                    "type": "string",
                    "example": "/testHttpService"
                },
                "ruleType": {
                    "description": "接入类型",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "serviceDesc": {
                    "description": "服务描述",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "我是一条测试"
                },
                "serviceIpFlowLimit": {
                    "description": "服务端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "serviceName": {
                    "description": "服务名称",
                    "type": "string",
                    "example": "test_http_service"
                },
                "upstreamConnectTimeout": {
                    "description": "连接超时",
                    "type": "integer",
                    "minimum": 0
                },
                "upstreamHeaderTimeout": {
                    "description": "获取Header超时",
                    "type": "integer",
                    "minimum": 0
                },
                "upstreamIdleTimeout": {
                    "description": "连接最大空闲时间",
                    "type": "integer",
                    "minimum": 0
                },
                "upstreamMaxIdle": {
                    "description": "最大空闲连接数",
                    "type": "integer",
                    "minimum": 0
                },
                "urlRewrite": {
                    "description": "url重写功能",
                    "type": "string"
                },
                "weightList": {
                    "description": "权重列表",
                    "type": "string",
                    "example": "50"
                },
                "whiteList": {
                    "description": "白名单",
                    "type": "string"
                }
            }
        },
        "dto.ServiceUpdateTcpInput": {
            "type": "object",
            "required": [
                "id",
                "ipList",
                "port",
                "serviceDesc",
                "serviceName",
                "weightList"
            ],
            "properties": {
                "blackList": {
                    "description": "黑名单",
                    "type": "string"
                },
                "clientIpFlowLimit": {
                    "description": "客户端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "forbidList": {
                    "description": "禁用IP列表",
                    "type": "string"
                },
                "id": {
                    "description": "服务编号",
                    "type": "integer",
                    "minimum": 1,
                    "example": 62
                },
                "ipList": {
                    "description": "ip列表",
                    "type": "string",
                    "example": "127.0.0.1:80"
                },
                "openAuth": {
                    "description": "是否开启权限",
                    "type": "integer",
                    "maximum": 1,
                    "minimum": 0
                },
                "port": {
                    "description": "端口",
                    "type": "integer",
                    "maximum": 8999,
                    "minimum": 8001,
                    "example": 8778
                },
                "roundType": {
                    "description": "轮询方式",
                    "type": "integer",
                    "maximum": 3,
                    "minimum": 0
                },
                "serviceDesc": {
                    "description": "服务描述",
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 1,
                    "example": "我是更新测试"
                },
                "serviceIpFlowLimit": {
                    "description": "服务端限流",
                    "type": "integer",
                    "minimum": 0
                },
                "serviceName": {
                    "description": "服务名称",
                    "type": "string",
                    "example": "test_tcp_update01"
                },
                "weightList": {
                    "description": "权重列",
                    "type": "string",
                    "example": "50"
                },
                "whiteHostName": {
                    "description": "白名单主机",
                    "type": "string"
                },
                "whiteList": {
                    "description": "白名单",
                    "type": "string"
                }
            }
        },
        "dto.StatItem": {
            "type": "object",
            "properties": {
                "load_type": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "dto.StatisticsOutput": {
            "type": "object",
            "required": [
                "today",
                "yesterday"
            ],
            "properties": {
                "today": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "yesterday": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.TokensInput": {
            "type": "object",
            "required": [
                "grant_type",
                "scope"
            ],
            "properties": {
                "grant_type": {
                    "description": "授权类型",
                    "type": "string",
                    "example": "client_credentials"
                },
                "scope": {
                    "description": "权限范围",
                    "type": "string",
                    "example": "read_write"
                }
            }
        },
        "dto.TokensOutput": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "access_token",
                    "type": "string"
                },
                "expires_in": {
                    "description": "expires_in",
                    "type": "integer"
                },
                "scope": {
                    "description": "scope",
                    "type": "string"
                },
                "token_type": {
                    "description": "token_type",
                    "type": "string"
                }
            }
        },
        "middleware.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errmsg": {
                    "type": "string"
                },
                "errno": {
                    "type": "integer"
                },
                "stack": {},
                "trace_id": {}
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
